#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

for my $event (qw(
    bootstrap-console-save
    console-save
    ))
{
    templates2events("/etc/phpMyAdmin/config.inc.php", $event);
    templates2events("/etc/e-smith/sql/init/80phpmyadmin", $event);
}

for my $event (qw(
   phpmyadmin-update 
   ))
{
    templates2events("/etc/httpd/conf/httpd.conf", $event);
    templates2events("/etc/phpMyAdmin/config.inc.php", $event);
    templates2events("/etc/e-smith/sql/init/80phpmyadmin", $event);
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/mysql.init");;
    safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith");
}
# PHP header and footer
 safe_symlink("/etc/e-smith/templates-default/template-begin-php", "root/etc/e-smith/templates/etc/phpMyAdmin/config.inc.php/template-begin");
 safe_symlink("/etc/e-smith/templates-default/template-end-php", "root/etc/e-smith/templates/etc/phpMyAdmin/config.inc.php/template-end");
